[package]
name = "screen-record"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
clap = { version = "3.1", features = [ "derive" ] }
eyre = "0.6"

